/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DepositRequest {
  'id' : string,
  'status' : DepositStatus,
  'user' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export type DepositStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface Transaction {
  'id' : string,
  'to' : Principal,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'from' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export type TransactionStatus = { 'pending' : null } |
  { 'autoCompleted' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'autoCompletedRejected' : null } |
  { 'rejected' : string };
export type TransactionType = { 'deposit' : null } |
  { 'internalTransfer' : null } |
  { 'purchase' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveDepositRequest' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDepositRequest' : ActorMethod<[bigint], string>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDepositRequests' : ActorMethod<[], Array<DepositRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTransactions' : ActorMethod<[Principal], Array<Transaction>>,
  'getWalletBalance' : ActorMethod<[Principal], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transferFunds' : ActorMethod<[Principal, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];