/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'autoCompleted' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'autoCompletedRejected' : IDL.Null,
  'rejected' : IDL.Text,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'internalTransfer' : IDL.Null,
  'purchase' : IDL.Null,
});
export const Time = IDL.Int;
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'to' : IDL.Principal,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'from' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DepositStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const DepositRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : DepositStatus,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveDepositRequest' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDepositRequest' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTransactions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getWalletBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transferFunds' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'autoCompleted' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'autoCompletedRejected' : IDL.Null,
    'rejected' : IDL.Text,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'internalTransfer' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const Time = IDL.Int;
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'to' : IDL.Principal,
    'status' : TransactionStatus,
    'transactionType' : TransactionType,
    'from' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DepositStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const DepositRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : DepositStatus,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveDepositRequest' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDepositRequest' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDepositRequests' : IDL.Func([], [IDL.Vec(DepositRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTransactions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getWalletBalance' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transferFunds' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };